### ISSUE TITLE
Feature Request: Select All Symbol Instances on a Page

### ISSUE THREAD

**Issue by ryanbelisle** [sonburn/symbol-instance-locator#1]
I'd love the ability to select all instances of a selected symbol, but just on a specific page. This would make it easy to swap out the symbol instances with a different symbol or symbol within a symbol library on a page by page basis.

**Comment by sonburn** [comment]
I saw your comment on Symbol Swapper and I can see what you are trying to do... I will see what I can do. I am working on another enhancement to Instance Locator as we speak.

**Comment by sonburn** [comment]
@ryanbelisle I added a Select All on Page button to v1.3, give it a whirl.

**Comment by ryanbelisle** [comment]
Sweet, I'll check it out asap! Thanks!
