### ISSUE TITLE
1.111 not working with large symbol library

### ISSUE THREAD

**Issue by chaosplan** [sonburn/symbol-instance-locator#10]
Amazing tool you've built. It gets almost daily use.

In 1.111 the Symbol Instance Locator dialog will not open when a known used symbol is selected. If no symbol is selected it does display the error dialog. This is happening with a large file that contains over 800 symbols (some deeply nested) and many pages and dartboards. Smaller files seem to work correctly.

I rolled back to 1.10 and the plugin works correctly on the large file.

Sorry, can't share the file - it's confidential.

**Comment by sonburn** [comment]
@chaosplan Mind checking your logs to see if an error appears?

	1.	Open Utilities > Console.app
 	2.	Expand ~/Library/Logs in the left window, and select **com.bohemiancoding.sketch3**
 	3.	Run the plugin in Sketch, if there was an error it will appear in the right window of Console, in a file called Plugin Output.log
 	4.	Copy/paste the output here

**Comment by jcohen292** [comment]
I've got the same issue. On larger files with a lot of symbols the pop-up window doesn't appear. But it does appear on smaller files with fewer symbols. Console error is the same: 

 «Plugin Output»
TypeError: null is not an object (evaluating 'overrides.forEach')
line: 427
sourceURL: /Users/jacobcohen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.cocoascript
column: 13
stack: getSymbolOverrides@/Users/Redacted/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.cocoascript:427:13
locate@/Users/Redacted/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.cocoascript:18:40
 «Plugin Output»

**Comment by afiqbinary** [comment]
I'm getting the same thing with same use case as @chaosplan 

```
TypeError: null is not an object (evaluating 'overrides.forEach')
line: 427
sourceURL: /Users/afiqsamat/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.cocoascript
column: 13
stack: getSymbolOverrides@/Users/afiqsamat/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.cocoascript:427:13
locate@/Users/afiqsamat/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.cocoascript:18:40
 «Plugin Output»
```

**Comment by sonburn** [comment]
@chaosplan, @jcohen292, @afiqbinary, thanks all for the feedback and apologies for taking so long to get back to this. I have just published an update which should address the issue. Please update to version 1.12 and let me know.

**Comment by jcohen292** [comment]
@sonburn Confirmed, it works. Thanks!

**Comment by sonburn** [comment]
@jcohen292 Great news, thanks for letting me know... and thanks for your patience!

**Comment by chaosplan** [comment]
@sonburn Also verified,  update 1.12 fixed the issue. This is a such great tool!

**Comment by sonburn** [comment]
Thanks guys, will close the issue.

**Comment by afiqbinary** [comment]
Thanks! 💃
