### ISSUE TITLE
Visual bug in Dark Mode - Mojave  

### ISSUE THREAD

**Issue by SaroGFX** [sonburn/symbol-instance-locator#20]
Sketch Version 59

![image](https://user-images.githubusercontent.com/3781800/67098075-c5218f00-f1bb-11e9-8aa4-eaeaa83c9c2d.png)

**Comment by tsilcher** [comment]
+1 For dark mode fix

**Comment by lmjabreu-poq** [comment]
+1

**Comment by Shoord** [comment]
+1, problem still occurs in MacOS Cataline unfortunately..

**Comment by sonburn** [comment]
@SaroGFX, @tsilcher, @Shoord I have just published a fix that should improve responsiveness, result accuracy, and better darkmode support. Also includes a fix for Sketch 72. Do you guys mind giving it a shot?

**Comment by Shoord** [comment]
@sonburn Hi Jason, the dark mode/legibility issue is fixed here! I'm running Sketch 72 on Big Sur. I wouldn't know about the other fixes, though.

**Comment by sonburn** [comment]
@Shoord Glad to hear it, I am going to close this issue. Thanks!
