### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by robertochiaveri** [sonburn/symbol-instance-locator#25]
When using Sketch in dark mode some of the UI becomes completely unreadable.

**Comment by sonburn** [comment]
@robertochiaveri I have just published a fix that should improve responsiveness, result accuracy, and better darkmode support. Also includes a fix for Sketch 72. Do you mind giving it a shot?

**Comment by sonburn** [comment]
Getting feedback from others that darkmode is fixed for them with the latest update, closing this issue.
