### ISSUE TITLE
Sketch 48 compatibility

### ISSUE THREAD

**Issue by dorian-grey** [sonburn/symbol-instance-locator#3]
Is kind of broken in Sketch 48:

- Doesn't jump to the symbol instance when selected in the list.

**Comment by sonburn** [comment]
@dorian-grey Resolved in version 1.7, thanks for calling it out.

**Comment by dorian-grey** [comment]
Thank you for this wonderful plugin - tremendous time saver!

**Comment by sonburn** [comment]
I am glad you find it valuable, and thank you very much for your donation!
