### ISSUE TITLE
Sketch 72 Can't scroll to bottom item

### ISSUE THREAD

**Issue by custa1200** [sonburn/symbol-instance-locator#31]
I am unable to scroll to the bottom of the list returned in Sketch 72.

**Comment by sonburn** [comment]
@custa1200 Can you elaborate a little more? Is the UI corrupt, or are you getting an error?

**Comment by custa1200** [comment]
Actually I may have posted this incorrectly on your myriad of Sketch plugins. :) I think it should be over on Symbol Swappper

**Comment by custa1200** [comment]
Actually I may have posted this incorrectly on your myriad of Sketch plugins. :) I think it should be over on Symbol Swappper

**Comment by custa1200** [comment]
https://github.com/sonburn/symbol-swapper/issues/58
