### ISSUE TITLE
finding instances in other files_ possible?

### ISSUE THREAD

**Issue by vnkulkarni** [sonburn/symbol-instance-locator#4]
Hello there, 1st of all Merry christmas! :)
and next is Thanks a Loottttt for the plugin.  :) :) 

well.. my issue is..
i am using a library file to which several other sketch files refer to for symbols.
with this plugin i can find all instances from same file but,
now my question is is there any way i can find instances of symbols which are there in other files? 
 [ v.n.kulkarni@gmail.com ]

**Comment by sonburn** [comment]
@vnkulkarni Sorry I am just now responding to this question.

This plugin will only search within the open/active document. If you want to search within a library file, you will have to open the library file and run the plugin with that file active.

Thank you for using Symbol Instance Locator!

**Comment by joshwand** [comment]
It would indeed be very useful when using a library to be able to see if any other files are using a symbol from that library. (e.g. can I safely delete or modify this library symbol?) 

If Sketch API allows, perhaps you could check in all currently-open files?
