### ISSUE TITLE
Plugin not running at all

### ISSUE THREAD

**Issue by seanoh1989** [sonburn/symbol-instance-locator#5]
Environment:
OSX El Capitan 10.11.6
Sketch 48.2 (latest as of now)
Symbol instance locator 1.7 (latest as of now)

When I select a layer and click Symbol Instance Locator from Plugins menu, Sketch does not do anything. It's not being slow or loading, it just does nothing.

Things I have tried
1. Reinstall Sketch (cache and old files included)
2. Remove and redownloaded the plugin
3. Used different design files

Has anyone experienced the same issue as me?

**Comment by seanoh1989** [comment]
I downloaded and installed Sketch 48 or 48.1, still no luck.

**Comment by lars-upstruct** [comment]
Same problem here. Did you solve it already?

**Comment by seanoh1989** [comment]
No, still same problem :(

**Comment by lars-upstruct** [comment]
At our studio it works on a machine with **Mac OS 10.12.6**
(same: Sketch 48.2, Symbol instance locator 1.7)

So it seems to be a **Mac OS 10.11** issue. Hmmm …

**Comment by sonburn** [comment]
@seanoh1989 and @lars-upstruct , sorry for taking so long to respond. I don't have El Capitan installed on any device, so if someone could provide a log event, it would be helpful. There are two ways to do this... Console.app or Terminal.

The Console.app changed in Sierra, and I don't recall the exact location of the log output back in El Cap, but in Sierra the log location is ~/Library/Logs/com.bohemiancoding.sketch3. Just open Sketch, run the plugin in your document, and check Plugin Output.log in the above location. This should give us a clue as to what failed.

The Terminal method is as follows. Close Sketch, and open Terminal, and enter the following "/Applications/Sketch.app/Contents/MacOS/Sketch" sans quotes. This will open Sketch and start logging within Terminal. Run the plugin in your document, and check output in the Terminal. This should give us a clue as to what failed.

**Comment by seanoh1989** [comment]
@sonburn  no problem. Thanks for getting back to us.

I ran the Sketch on Terminal to get this log

    ```
Mar 29 15:17:37  Symbol Instance Locator (Sketch)[35330] <Notice>: SyntaxError: Unexpected token '>'.
	Plugin “script”, line 88:
	» 					var buttonToSelect = symbolType.findIndex(o => o == pageInstance);
2018-03-29 15:17:37.892 Sketch[35330:1037053] Exception: {
    line = 88;
    sourceURL = "/Users/Sean/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Locator.sketchplugin/Contents/Sketch/script.cocoascript";
}
```

**Comment by sonburn** [comment]
@seanoh1989 Thank you, this was very helpful. I will see what I can do.

**Comment by sonburn** [comment]
@seanoh1989 and @lars-upstruct , could you please try the updated plugin at the link below? I would like to verify it works before publishing.

https://www.dropbox.com/sh/h3nzkfnoxmg7uxq/AAD9SbhzG4VSBHltGBXX1yRGa?dl=0

**Comment by seanoh1989** [comment]
@sonburn looks like getting replacing that inline function worked! I can verify the fix. Thanks a lot 👍

**Comment by sonburn** [comment]
@seanoh1989 Happy to hear it, sorry again for taking so long to get to this. I just published this update for the masses. Thanks for bringing it to my attention, and for using the plugin!
