### ISSUE TITLE
Does not work with symbols used as a shared library

### ISSUE THREAD

**Issue by dennishansen** [sonburn/symbol-instance-locator#7]

**Comment by sonburn** [comment]
@dennishansen This plugin works with any symbol or instance in your document, regardless of the location of your symbol master (local or in a library). The plugin requires you have something to select though, and there is a use case where you use a library symbol as an override, which doesn't give you anything local in your document to select. In that situation, I usually add another version of that instance to my document somewhere, select it and run the plugin, then you will be able to locate those stubborn instances only used as overrides, take action, and then delete the new one you added to run the plugin. Hope this helps!

**Comment by dennishansen** [comment]
That's a good idea, thanks!
