### ISSUE TITLE
Sketch Crashes after selecting all on page

### ISSUE THREAD

**Issue by riacharda** [sonburn/symbol-instance-locator#8]
Hi,

After I find all symbol instances, select all on a page then change an override, Sketch crashes then closes down. 

When I relaunch Sketch, it opens in safe mode and all plugins get disabled.

**Comment by sonburn** [comment]
@riacharda thanks for the feedback. I am unable to reproduce this, do you have an example file you could share, or if not, can you recreate this issue in a file you can share?

**Comment by sonburn** [comment]
@riacharda Sketch version, plugin version, and Mac version would also be helpful.

**Comment by riacharda** [comment]
Hi Jason,

I updated my version of Sketch to 51.1 this morning. This issue no longer
happens anymore.

Sorry for not giving much detail.

Regards,
Richard
